### PR TITLE
Accessible config as dict

### PR DESCRIPTION
**Pull request by casper-hansen**
Here is a PR to make it *a bit easier* to observe the configuration across different experiments. This is generally useful for MLOps to observe the exact configuration of your training run.

For example, this makes it easier for a user to extend the code and log the config in Weights & Biases:

```
wandb.init(config=job_config.to_dict())
```

### CODE REVIEW

**Comment by awgu** [comment]
seems ok to me
will let @tianyu-l review

**Review by tianyu-l — APPROVED** [review]
lgtm. Thank you!

**Comment by casper-hansen** [comment]
@tianyu-l I just merged main branch into my PR to clear the CI. It looks like a green check from the CI is the last step before this can be merged.

**Comment by awgu** [comment]
@casper-hansen I re-triggered CI

**Pull request merged**
