### PR TITLE
Fix parsing of pp split points from toml file

### PR DESCRIPTION
**Pull request by wconstab**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #664
* __->__ #450

Previously, string_list formatting was only applied to pp split points
arg when it came from the cmd line.  The string_list formatting needs to
be applied when loading via toml too.

### CODE REVIEW

**Comment by fduwjj** [comment]
why the integration test failed?

**Comment by wconstab** [comment]
I think I fixed this.  I added a comment along with the fix.  The string_list thing was getting applied a second time in the case that the user passed the split-points on the cmd line.  The fix is to only apply the string_list after toml loading _IF_ the split-points arg is of string type, but leave it alone if it's a list.

**Review by H-Huang — APPROVED** [review]
Looks good. The 4-GPU test failure is unrelated, it's due to a bad base commit which has since been fixed

**Review by tianyu-l — COMMENTED** [review]
can we add a unit test for this in https://github.com/pytorch/torchtitan/blob/main/test/test_job_config.py?

Currently in CI there is no test cases using `pipeline_parallel_split_points` anymore, since @H-Huang has made it not requiring one in https://github.com/pytorch/torchtitan/pull/604.

**Pull request merged**
