### PR TITLE
Update requirements.txt

### PR DESCRIPTION
**Pull request by qiziAI**
conflict with the install.

### CODE REVIEW

**Comment by awgu** [comment]
@qiziAI Thanks for the PR! Could you provide some more details of the conflict for our understanding?

**Comment by qiziAI** [comment]
> @qiziAI Thanks for the PR! Could you provide some more details of the conflict for our understanding?

Yes. If I installed torch 2.3.0 by using pip, then run `pip install -r requirements.txt`.  The torch version is still 2.3.0 not 2.2.0 dev or any other dev version that >= 2.2.0.

`Requirement already satisfied: torch>=2.2.0.dev in ./venv2/lib/python3.10/site-packages (from -r requirements.txt (line 1)) (2.3.0)`

 This causes error occurs when execute run_llama_train.sh script :

`ImportError: cannot import name '_copy_state_dict' from 'torch.distributed._state_dict_utils'`

Hope this details can help.

**Comment by LucasLLC** [comment]
Shouldn't this be updated to `torch==2.3.1` or the correct version which includes `_copy_state_dict` ?

**Comment by qiziAI** [comment]
> Shouldn't this be updated to `torch==2.3.1` or the correct version which includes `_copy_state_dict` ?

Indeed, the purpose of this PR is to point out that the line 'torch >= 2.2.0 dev' in requirements.txt does not guarantee the installation of a torch version containing the '_copy_state_dict' function as you mentioned. That's the issue.

**Comment by tianyu-l** [comment]
@qiziAI Thanks for pointing this out!
Since the newly added import "_copy_state_dict" is not used by default, we don't necessarily need to require the most recent pytorch. This is fixed in #333.

**Comment by qiziAI** [comment]
@tianyu-l Great! Thanks!

**Pull request closed without merging**
