### PR TITLE
enable TritonFusedRMSNorm with local_map annotation

### PR DESCRIPTION
**Pull request by XilunWu**
Summary
This PR enables the use of TritonFusedRMSNorm with Tensor Parallel with 7%-8% performance gain compared to RMSNorm with TP. #364

### CODE REVIEW

**Comment by XilunWu** [comment]
#364 is created from `ghstack`. Create this PR to merge from `base` branch into `main`.

**Review by wanchaol — APPROVED** [review]

**Comment by fabianlim** [comment]
I get an error  `cannot import name 'Partial' from 'torch.distributed._tensor'` on torch=2.3.1. It seems `Partial` is available only for nightly torch?

**Comment by XilunWu** [comment]
@fabianlim That's true. `Partial` is added in pytorch 2.4

**Comment by wanchaol** [comment]
> I get an error `cannot import name 'Partial' from 'torch.distributed._tensor'` on torch=2.3.1. It seems `Partial` is available only for nightly torch?

@fabianlim curious if you are using fused_rmsnorm or not? currently torchtitan is evolving and depending on nightlies, we'll start committing to BC with code releases. If you want to unblock, you can either use a older commit, or do some simple changes in this file https://github.com/pytorch/torchtitan/blob/main/torchtitan/models/norms.py#L17

from
```
from torch.distributed._tensor import Partial, Replicate, Shard
```
to
```
from torch.distributed._tensor import Replicate, Shard
from torch.distributed._tensor.placement_types import _Partial 
```

**Comment by fabianlim** [comment]
@XilunWu yea i brought it up beacuse it is not clear from the requirements file that it was only for nightly torch https://github.com/pytorch/torchtitan/blob/main/.ci/docker/requirements.txt#L1

@wanchaol yea i downgraded and Im fine now

**Pull request merged**
