### PR TITLE
[TP] Infer local n_heads instead of ad-hoc model changes

### PR DESCRIPTION
**Pull request by kwen2501**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #498

Today we modify model attributes `n_heads` and `n_kv_heads` after applying TP, which is also after the model's creation.

https://github.com/pytorch/torchtitan/blob/e457deb080e7c5eaa461ff03cfab7b1b8b55e583/torchtitan/parallelisms/parallelize_llama.py#L401-L404

The ad-hoc modification is for the following code to work in TP case:
https://github.com/pytorch/torchtitan/blob/e457deb080e7c5eaa461ff03cfab7b1b8b55e583/torchtitan/models/llama/model.py#L193-L195
because the `n_heads` and `n_kv_heads` per rank are different from the non-TP case.

This has a couple side-effects:
- requires an application runner (not necessarily the model author) to be familiar with the model's details as well as the consequence of TP;
- renders the TP APIs less standalone;
- hard to compose with pipeline parallel, in particular if the user uses the tracing frontend -- the attribute modification may be non-effective or the attributes not available.

Fortunately, `view` ops has a nice feature that a size of -1 can be inferred from other dimensions. This PR thus utilizes that to make the code generally workable for both TP and non-TP cases.

### CODE REVIEW

**Review by lessw2020 — APPROVED** [review]
very nice!  This might resolve the PP dilemma re: TP and tracing.  
I ran it with async tp as well just to make sure no issues, and verify no perf change, works great.

**Comment by fduwjj** [comment]
Is it because changing the attribute makes tracing not working? Instead of using -1, since DTensor now supports pretty much all attention ops. Shall we go full DTensor mode inside attention so that no module attribute is needed? @tianyu-l @wanchaol

**Comment by kwen2501** [comment]
Tracing (PP) today happens before TP hence before the attribute change. And it would "burn" known attribute values into the traced model. That's why "after-trace" attribute change would not be effective.

I think "-1" would work for DTensor's view op too :)

**Comment by kwen2501** [comment]
There are indeed pros and cons of keeping the result in DTensor form vs local form. I'd like to learn from any discussion you may have.

**Comment by tianyu-l** [comment]
(some of) 4 GPU integration tests are failing. @kwen2501 can you check if it's caused by this
https://github.com/pytorch/torchtitan/actions/runs/10220000239

**Comment by tianyu-l** [comment]
> Is it because changing the attribute makes tracing not working? Instead of using -1, since DTensor now supports pretty much all attention ops. Shall we go full DTensor mode inside attention so that no module attribute is needed? @tianyu-l @wanchaol

@fduwjj 
Currently there's an issue #267 blocking full DTensor mode. After fixing the issue, we should be good even without this PR's change.

**Comment by kwen2501** [comment]
> (some of) 4 GPU integration tests are failing. @kwen2501 can you check if it's caused by this https://github.com/pytorch/torchtitan/actions/runs/10220000239

Hmm, there is a tracer error in that CI run above.
Interestingly, when I merge this PR (yesterday), the CI is all green. And it seems unlikely that the "-1" change would make export uncomfortable. (Export likes determinism too.)
I wonder if there is some other change that may cause the failure -- like a change in pytorch nightly?

Btw, it seems the trunk of titan is still healthy.

**Pull request merged**
