### PR TITLE
Fix 1D PP tracer test

### PR DESCRIPTION
**Pull request by wconstab**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #362

forgot to enable tracer for tracer test in the last PR

### CODE REVIEW

**Review by kwen2501 — APPROVED** [review]
Made a small change:
In tracer mode, we don't require users to provide manual split points, because that is being taken care of by the `pipeline_llama_tracer` function today:
https://github.com/pytorch/torchtitan/blob/54b5fa259d8dd6c55c044a536b949363e31ee9f9/torchtitan/parallelisms/parallelize_llama.py#L272-L276

**Comment by kwen2501** [comment]
CI should pass after https://github.com/pytorch/pytorch/pull/127607 is landed.

**Comment by wconstab** [comment]
> Made a small change:
In tracer mode, we don't require users to provide manual split points, because that is being taken care of by the pipeline_llama_tracer function today:

I think this is not the right way to do this.  If we want the layer-split to be 'automatic', i think it should be automatic for both frontends, and we can delete the _split_points cmdline arg.

or if we want to have the cmdline arg, we should keep it behaving the same for both frontends.

I'd propose to first keep the arg for both frontends, and then do a PR that makes the cmdline arg optional and uses automation for both PRs.

**Comment by kwen2501** [comment]
Sounds good to me

**Review by kwen2501 — APPROVED** [review]
Re-approve

**Pull request merged**
